In [6]:
import pandas as pd

In [7]:
ds = pd.read_csv("../pokemone.csv")
print(ds)

      No       Name    Type1   Type2  Height  Weight  Legendary
0      1  Bulbasaur    Grass  Poison     0.7     6.9          0
1      1  Bulbasaur    Grass  Poison     0.7     6.9          0
2      1  Bulbasaur    Grass  Poison     0.7     6.9          0
3      1  Bulbasaur    Grass  Poison     0.7     6.9          0
4      1  Bulbasaur    Grass  Poison     0.7     6.9          0
..   ...        ...      ...     ...     ...     ...        ...
181  146    Moltres     Fire  Flying     2.0    60.0          1
182  147    Dratini   Dragon     NaN     1.8     3.3          0
183  148  Dragonair   Dragon     NaN     4.0    16.5          0
184  149  Dragonite   Dragon  Flying     2.2   210.0          0
185  150     Mewtwo  Psychic     NaN     2.0   122.0          1

[186 rows x 7 columns]

In [8]:
print(ds.mean(numeric_only=True))

No           65.575269
Height        1.127419
Weight       40.640860
Legendary     0.021505
dtype: float64

In [9]:
print(ds.sum(numeric_only=True))

No           12197.0
Height         209.7
Weight        7559.2
Legendary        4.0
dtype: float64

In [10]:
print(ds.min(numeric_only=True))

No           1.0
Height       0.2
Weight       0.1
Legendary    0.0
dtype: float64

In [11]:
print(ds.max(numeric_only=True))

No           150.0
Height         8.8
Weight       460.0
Legendary      1.0
dtype: float64

In [12]:
print(ds.count())

No           186
Name         186
Type1        186
Type2         83
Height       186
Weight       186
Legendary    186
dtype: int64

In [13]:
#single coloumn agregate function

In [14]:
print(ds["Height"].sum())
print(ds["Height"].max())

209.7
8.8

In [15]:
group = ds.groupby("Type1")

print(group["Height"].mean())

Type1
Bug         0.958824
Dragon      2.666667
Electric    0.855556
Fairy       0.988889
Fighting    1.185714
Fire        1.070000
Ghost       1.466667
Grass       0.942105
Ground      0.850000
Ice         1.550000
Normal      0.877419
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64

In [16]:
group = ds.groupby("Type1")

print(group["Weight"].mean())

Type1
Bug         25.641176
Dragon      76.600000
Electric    31.788889
Fairy       25.555556
Fighting    54.285714
Fire        34.775000
Ghost       13.566667
Grass       20.221053
Ground      45.262500
Ice         48.000000
Normal      39.238710
Poison      27.314286
Psychic     58.357143
Rock        87.611111
Water       57.967857
Name: Weight, dtype: float64

In [17]:
group = ds.groupby("Type1")
print(group["Height"].sum())

Type1
Bug         16.3
Dragon       8.0
Electric     7.7
Fairy        8.9
Fighting     8.3
Fire        21.4
Ghost        4.4
Grass       17.9
Ground       6.8
Ice          3.1
Normal      27.2
Poison      17.1
Psychic      9.6
Rock        16.6
Water       36.4
Name: Height, dtype: float64

In [18]:
group = ds.groupby("Type1")
print(group["Height"].mean())

Type1
Bug         0.958824
Dragon      2.666667
Electric    0.855556
Fairy       0.988889
Fighting    1.185714
Fire        1.070000
Ghost       1.466667
Grass       0.942105
Ground      0.850000
Ice         1.550000
Normal      0.877419
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64

In [19]:
group = ds.groupby("Type1")
print(group["Height"].count())

Type1
Bug         17
Dragon       3
Electric     9
Fairy        9
Fighting     7
Fire        20
Ghost        3
Grass       19
Ground       8
Ice          2
Normal      31
Poison      14
Psychic      7
Rock         9
Water       28
Name: Height, dtype: int64

In [27]:
water = ds.groupby("Type1")["Weight"].median()
print(water)

Type1
Bug         30.00
Dragon      16.50
Electric    30.00
Fairy       40.00
Fighting    49.80
Fire        19.90
Ghost        0.10
Grass        6.90
Ground      31.40
Ice         48.00
Normal      18.50
Poison      19.75
Psychic     54.50
Rock        40.50
Water       37.50
Name: Weight, dtype: float64

In [33]:
height_agg = ds.groupby("Type1")["Height"].agg(["mean","median","count"])
height_agg

              mean  median  count
Type1
Bug       0.958824    1.10     17
Dragon    2.666667    2.20      3
Electric  0.855556    0.80      9
Fairy     0.988889    1.30      9
Fighting  1.185714    1.40      7
Fire      1.070000    1.10     20
Ghost     1.466667    1.50      3
Grass     0.942105    0.70     19
Ground    0.850000    0.85      8
Ice       1.550000    1.55      2
Normal    0.877419    0.70     31
Poison    1.221429    1.05     14
Psychic   1.371429    1.30      7
Rock      1.844444    1.00      9
Water     1.300000    1.10     28

In [42]:
height_100 = ds.groupby("Type1").filter(lambda group: (group["Height"] > 100).any())
height_100

Empty DataFrame
Columns: [No, Name, Type1, Type2, Height, Weight, Legendary]
Index: []